// generated by p4gen from '/home/gk/ws/ans-vm/share/dpc/configs/dpc-soft-switch.json'

#define DPA_NS 1
#define TOFINO 1
#define TOFINO_MODEL 1
#define PIPE_0 0
#define PIPE_1 1
#define PIPE_2 2
#define PIPE_3 3
#define DPA_PORT 4241
#define DPA_PIPES 4
#define DPA_EXPONENTS 4
#define DPA_REDUCERS 32
#define DPA_REDUCER_MODE 2
#define DPA_REDUCER_SLOTS 16384
#define DPA_VALUE_WIDTH 4
#define DPA_SESSIONS_MAX 1
#define DPA_COUNTERS 1
#define DPA_BACKWARD_PORT 56

#include "/home/gk/ws/ans-vm/share/dpc/test.p4"
