
from typing import Optional

class DeviceConfig: ...
class BackendConfig: ...

class Options:
    device: Optional[DeviceConfig]
    backend: Optional[BackendConfig]
    hint_pinned_tensor_size: int
    hint_pinned_tensor_pool_size: int
    def __init__(self) -> None: ...

def pin_away() -> list[int]: ...
def get_pinned_cores() -> list[int]: ...
def get_available_cores() -> list[int]: ...
