#!/usr/bin/env python3
"""Generate the DPA switch P4 entry file from a flat device config JSON."""

import argparse
import json
import os
import sys

# Fields exported as DPA_<KEY> defines — this table IS the P4 interface.
EXPORTS = ["port", "pipes", "exponents", "reducers", "reducer_mode",
           "reducer_slots", "value_width", "sessions_max", "counters", "backward_port"]


def generate(config_path: str, main_path: str, output_path: str, verbose: bool = False):
    config_path = os.path.abspath(config_path)
    main_path = os.path.abspath(main_path)
    output_path = os.path.abspath(output_path)

    if not os.path.exists(main_path):
        raise FileNotFoundError(f"main P4 not found: {main_path}")

    with open(config_path) as f:
        cfg = json.load(f)

    missing = [k for k in EXPORTS if k not in cfg]
    if missing:
        raise KeyError(f"config missing fields: {', '.join(missing)}")

    def define(k, v):
        return f"#define {k.upper()} {int(v) if isinstance(v, bool) else v}"

    lines = [f"// generated by p4gen from '{config_path}'", ""]
    if not cfg.get("straggle_aware", False):
        lines.append(define("DPA_NS", 1))
    lines.append(define("TOFINO", cfg.get("tofino", 1)))
    lines.append(define("TOFINO_MODEL", not cfg.get("asic", False)))
    for i, p in enumerate(cfg.get("pipe_config", range(cfg["pipes"]))):
        lines.append(define(f"PIPE_{i}", int(p)))
    for k in EXPORTS:
        lines.append(define(f"DPA_{k}", cfg[k]))
    lines += ["", f'#include "{main_path}"', ""]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    if verbose:
        print(f"p4gen: {config_path} + {main_path} -> {output_path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Generate DPA switch P4 entry file")
    ap.add_argument("main", help="main P4 source file")
    ap.add_argument("-c", "--config", required=True, help="flat device config JSON")
    ap.add_argument("-o", "--output", required=True, help="output P4 file")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    try:
        generate(args.config, args.main, args.output, args.verbose)
    except Exception as e:
        sys.exit(f"p4gen: error: {e}")
