#ifndef DPC_TOOLS_DPC_SWITCH_UTILS_H
#define DPC_TOOLS_DPC_SWITCH_UTILS_H

#include "fmt/core.h"

#include <atomic>
#include <cstdint>
#include <deque>
#include <iostream>
#include <map>
#include <mutex>
#include <ncurses.h>
#include <optional>
#include <string>

struct Stats {
  using clock_t = std::chrono::high_resolution_clock;
  std::mutex mu;

  struct in_t {
    uint64_t bytes = 0;
    uint64_t pkts = 0;
    uint64_t pkts_rtx = 0;
    uint64_t pkts_ign = 0;
    std::map<std::string, uint64_t> pkts_by_src; // "host (ip)" -> packets
  } in{};
  struct out_t {
    uint64_t bytes = 0; // total bytes (unicast + multicast)
    uint64_t mcast = 0;
    uint64_t ucast = 0;
    std::map<std::string, uint64_t> pkts_by_src; // "host (ip)" -> unicast packets
  } out{};
  clock_t::time_point start = clock_t::now();

  void record_in(uint64_t len, const std::string &src, bool rtx = false) {
    std::lock_guard<std::mutex> l(mu);
    in.bytes += len;
    in.pkts++;
    in.pkts_rtx += rtx;
    in.pkts_by_src[src]++;
  }

  void record_out(uint64_t len, uint16_t receivers = 1) {
    std::lock_guard<std::mutex> l(mu);
    out.ucast += (receivers == 1);
    out.mcast += (receivers != 1);
    out.bytes += len * receivers;
  }

  void record_in_ignored(uint64_t size) {
    std::lock_guard<std::mutex> l(mu);
    in.pkts_ign++;
  }

  void clear() {
    std::lock_guard<std::mutex> l(mu);
    in.pkts_by_src.clear();
    in = {};
    out = {};
  }

  void dump() {
    std::lock_guard<std::mutex> lk(mu);
    auto secs = std::chrono::duration_cast<std::chrono::seconds>(clock_t::now() - start).count();

    fmt::println("=== stats ===\n");
    fmt::println("uptime : {}s", secs);
    fmt::println("in:\n  packets: {} ({} rtx, {} ignored)\n  bytes  : {}", in.pkts, in.pkts_rtx, in.pkts_ign, in.bytes);
    if (!in.pkts_by_src.empty()) {
      fmt::println("    by source:\n");
      for (auto &[k, v] : in.pkts_by_src) fmt::println("    {} : {}", k, v);
    }
    fmt::println("out:\n  mcast: {}\n  ucast: {}\n  bytes: {}", out.mcast, out.ucast, out.bytes);
    if (!out.pkts_by_src.empty()) {
      fmt::println("  by source:\n");
      for (auto &[k, v] : out.pkts_by_src) fmt::println("    {} : {}", k, v);
    }
    fmt::println("");
  }
};

inline void cli_controller(Stats &stats, std::atomic<bool> &running) {
  fmt::print("controller ready. commands: help, dump, clear, stop\n> ");
  std::string line;
  while (running.load() && std::getline(std::cin, line)) {
    // trim
    size_t a = line.find_first_not_of(" \t\r\n");
    size_t b = line.find_last_not_of(" \t\r\n");
    std::string cmd = (a == std::string::npos) ? "" : line.substr(a, b - a + 1);

    if (cmd.empty()) {
      // nothing
    } else if (cmd == "help" || cmd == "?" || cmd == "h") {
      fmt::println("  help   - this\n");
      fmt::println("  stats  - print stats\n");
      fmt::println("  clear  - print stats\n");
      fmt::println("stop   - shut down the switch\n");
    } else if (cmd == "stats" or cmd == "stat" or cmd == "s") {
      stats.dump();
    } else if (cmd == "stats clear") {
      stats.clear();
      fmt::println("stats cleared\n");
    } else if (cmd == "stop" || cmd == "quit" || cmd == "exit" || cmd == "q") {
      fmt::println("stopping...\n");
      running.store(false);
      break;
    } else {
      fmt::println("unknown command: {} (try 'help')", cmd);
      // std::cout << "unknown command: " << cmd << " (try 'help')\n";
    }
    if (running.load()) fmt::print("> "); // std::cout << "> " << std::flush;
  }
  running.store(false); // EOF on stdin also stops us
}

// Generated by Claude
//
// SwitchConsole -- two panes + one prompt line. Fully native mouse:
// wheel scrolls the dataplane pane, drag selects, right-click works.
// switch_console.h
//
// SwitchConsole -- two scrollable panes + one prompt line. MOUSE MODE:
//
//   Wheel over a pane     : scroll that pane's history
//   Drag the divider line : resize panes
//   Terminal resize       : layout reflows, history kept
//   Text selection        : Option+drag (iTerm2) / Shift+drag (xterm etc).
//                           Zed's terminal does not support this bypass.
//
// Exit cleanly (stop command or Ctrl+C with the SIGINT handler installed)
// or the terminal may be left in mouse mode -- fix with `reset`.
class SwitchConsole {
public:
  class Dataplane {
  public:
    void log(const std::string &s) { con_->put(con_->dp_, s); }

  private:
    friend class SwitchConsole;
    SwitchConsole *con_;
  };

  class Controller {
  public:
    void log(const std::string &s) { con_->put(con_->ctl_, s); }
    std::optional<std::string> read_line(const std::atomic<bool> &running) { return con_->read_line(running); }

  private:
    friend class SwitchConsole;
    SwitchConsole *con_;
  };

  Dataplane dataplane;
  Controller controller;

  explicit SwitchConsole(int controller_h = 8, int poll_ms = 200) : poll_ms_(poll_ms) {
    initscr();
    cbreak();
    noecho();
    getmaxyx(stdscr, h_, w_);
    if (controller_h > h_ - 5) controller_h = h_ / 3;

    dp_.rows = h_ - controller_h - 2; // dataplane | divider | controller | prompt
    dp_.top = 0;
    dp_.win = newwin(dp_.rows, w_, 0, 0);

    div_ = newwin(1, w_, dp_.rows, 0);
    draw_divider();

    ctl_.rows = controller_h;
    ctl_.top = dp_.rows + 1;
    ctl_.win = newwin(ctl_.rows, w_, ctl_.top, 0);

    in_ = newwin(1, w_, h_ - 1, 0);
    keypad(in_, TRUE);
    wtimeout(in_, poll_ms_); // wgetch -> ERR tick, so shutdown can't hang

    // mouse reporting: wheel + button1 press/release + motion while held
    mousemask(BUTTON1_PRESSED | BUTTON1_RELEASED | REPORT_MOUSE_POSITION | BUTTON4_PRESSED | BUTTON5_PRESSED, nullptr);
    mouseinterval(0);
    std::printf("\033[?1002h"); // motion-while-button-held tracking
    std::fflush(stdout);

    dataplane.con_ = this;
    controller.con_ = this;
    prompt();
  }

  ~SwitchConsole() {
    mousemask(0, nullptr);      // ncurses: stop mouse reporting
    endwin();                   // restore terminal modes
    std::printf("\033[?1002l"); // then drop motion tracking
    std::fflush(stdout);
  }
  SwitchConsole(const SwitchConsole &) = delete;
  SwitchConsole &operator=(const SwitchConsole &) = delete;

private:
  static constexpr size_t kHistory = 5000;

  struct Pane {
    WINDOW *win = nullptr;
    int rows = 0;
    int top = 0;
    std::deque<std::string> lines;
    int scroll = 0; // 0 = pinned to tail

    int max_scroll() const {
      int m = static_cast<int>(lines.size()) - rows;
      return m > 0 ? m : 0;
    }
    bool contains(int y) const { return y >= top && y < top + rows; }
  };

  // ---- drawing (callers hold mu_) ---------------------------------------

  void draw_divider() {
    werase(div_);
    mvwhline(div_, 0, 0, ACS_HLINE, w_);
    wrefresh(div_);
  }

  void repaint(Pane &p) {
    werase(p.win);
    int total = static_cast<int>(p.lines.size());
    int end = total - p.scroll;
    int start = end - p.rows;
    if (start < 0) start = 0;
    for (int i = start; i < end; ++i) mvwaddnstr(p.win, i - start, 0, p.lines[i].c_str(), w_);
    if (p.scroll > 0) {
      std::string tag = "-- " + std::to_string(p.scroll) + " more below --";
      mvwaddnstr(p.win, p.rows - 1, 0, tag.c_str(), w_);
    }
    wrefresh(p.win);
    wrefresh(in_);
  }

  void prompt() {
    werase(in_);
    mvwprintw(in_, 0, 0, "ctl> ");
    wrefresh(in_);
  }

  // ---- pane operations -----------------------------------------------------

  void put(Pane &p, const std::string &s) { // any thread
    std::lock_guard<std::mutex> lk(mu_);
    p.lines.push_back(s);
    if (p.lines.size() > kHistory) {
      p.lines.pop_front();
      if (p.scroll > 0 && p.scroll < p.max_scroll()) ++p.scroll;
    }
    if (p.scroll == 0) repaint(p);
  }

  void scroll_pane(Pane &p, int delta) { // delta > 0 = older lines
    int s = p.scroll + delta;
    if (s < 0) s = 0;
    if (s > p.max_scroll()) s = p.max_scroll();
    if (s == p.scroll) return;
    p.scroll = s;
    repaint(p);
  }

  void set_divider(int y) { // y = divider's new screen row
    if (y < 3 || y > h_ - 5) return;
    if (y == dp_.rows) return;
    dp_.rows = y;
    ctl_.rows = h_ - y - 2;
    ctl_.top = y + 1;
    wresize(dp_.win, dp_.rows, w_);
    mvwin(ctl_.win, ctl_.top, 0);
    wresize(ctl_.win, ctl_.rows, w_);
    mvwin(div_, y, 0);
    if (dp_.scroll > dp_.max_scroll()) dp_.scroll = dp_.max_scroll();
    if (ctl_.scroll > ctl_.max_scroll()) ctl_.scroll = ctl_.max_scroll();
    repaint(dp_);
    repaint(ctl_);
    draw_divider();
  }

  void handle_resize() { // rebuild layout for new terminal size
    getmaxyx(stdscr, h_, w_);
    int ctl_h = ctl_.rows;
    if (ctl_h > h_ - 5) ctl_h = h_ / 3;
    if (ctl_h < 3) ctl_h = 3;
    dp_.rows = h_ - ctl_h - 2;
    ctl_.rows = ctl_h;
    ctl_.top = dp_.rows + 1;

    delwin(dp_.win);
    delwin(div_);
    delwin(ctl_.win);
    delwin(in_);
    clear();
    refresh();

    dp_.win = newwin(dp_.rows, w_, 0, 0);
    div_ = newwin(1, w_, dp_.rows, 0);
    ctl_.win = newwin(ctl_.rows, w_, ctl_.top, 0);
    in_ = newwin(1, w_, h_ - 1, 0);
    keypad(in_, TRUE);
    wtimeout(in_, poll_ms_);

    if (dp_.scroll > dp_.max_scroll()) dp_.scroll = dp_.max_scroll();
    if (ctl_.scroll > ctl_.max_scroll()) ctl_.scroll = ctl_.max_scroll();
    repaint(dp_);
    repaint(ctl_);
    draw_divider();
  }

  // ---- input ------------------------------------------------------------------

  Pane *pane_at(int y) {
    if (dp_.contains(y)) return &dp_;
    if (ctl_.contains(y)) return &ctl_;
    return nullptr;
  }

  void handle_mouse() {
    MEVENT ev;
    if (getmouse(&ev) != OK) return;

    if (ev.bstate & BUTTON1_PRESSED) {
      dragging_ = (ev.y == dp_.rows); // only the divider is grabbable
    } else if (ev.bstate & BUTTON1_RELEASED) {
      dragging_ = false;
    } else if (dragging_ && (ev.bstate & REPORT_MOUSE_POSITION)) {
      set_divider(ev.y);
    } else if (ev.bstate & (BUTTON4_PRESSED | BUTTON5_PRESSED)) {
      int d = (ev.bstate & BUTTON4_PRESSED) ? +3 : -3;
      if (Pane *p = pane_at(ev.y)) scroll_pane(*p, d);
    }
  }

  std::optional<std::string> read_line(const std::atomic<bool> &running) {
    std::string s;
    while (true) {
      int c = wgetch(in_); // no lock held while waiting
      if (c == ERR) {      // poll tick
        if (!running.load()) return std::nullopt;
        continue;
      }
      std::lock_guard<std::mutex> lk(mu_);
      if (c == KEY_MOUSE) {
        handle_mouse();
      } else if (c == KEY_RESIZE) {
        handle_resize();
        prompt();
        waddnstr(in_, s.c_str(), -1); // restore partially typed command
        wrefresh(in_);
      } else if (c == '\n' || c == '\r' || c == KEY_ENTER) {
        prompt();
        return s;
      } else if (c == KEY_BACKSPACE || c == 127 || c == 8) {
        if (!s.empty()) {
          s.pop_back();
          int y, x;
          getyx(in_, y, x);
          mvwaddch(in_, y, x - 1, ' ');
          wmove(in_, y, x - 1);
          wrefresh(in_);
        }
      } else if (c >= 32 && c < 127) {
        s.push_back(static_cast<char>(c));
        waddch(in_, c);
        wrefresh(in_);
      }
    }
  }

  Pane dp_, ctl_;
  WINDOW *div_ = nullptr;
  WINDOW *in_ = nullptr;
  bool dragging_ = false;
  int h_ = 0, w_ = 0;
  int poll_ms_ = 200;
  std::mutex mu_;
};

#endif // DPC_TOOLS_DPC_SWITCH_UTILS_H
